language: node_js

node_js:
  - "node"

notifications:
  email: false

  
addons:
  apt:
    packages:
    - libgconf-2-4

cache:
  directories:
    - ~/.npm
    - ~/.cache
  
  override:
    - npm ci
    - npm run cy:verify

script:
  # start server in the background
  - npm start &
  # run all Cypress tests and record on the dashboard
  - npm run cypress:run
  # after all tests finish running we need
  # to kill all background jobs (like "npm start &")
  # this avoids flake in Travis jobs
  - kill $(jobs -p) || true

